### ISSUE TITLE
"返回 like.co" button

### ISSUE THREAD

**Issue by edmondyu** [likecoin/migrate-to-likecoin-chain#32]
Migration 完成後，點擊「返回 like.co」按鍵，回到 like.co/in 後，彈出如下的畫面。

![image](https://user-images.githubusercontent.com/17264698/70022639-d38f0300-15cf-11ea-9c3f-ec6364a79df2.png)

**Comment by williamchong007** [comment]
Fixed by https://github.com/likecoin/likecoin-store/pull/1322
